### ISSUE TITLE
Reveal affect missing in Classic Mode branch

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#32]
The reveal border affect is missing from items in drop down combo boxes in the Classic Mode branch.

**Comment by ray1997** [comment]
I just notice it now that reveal effect is gone from the whole app and as I bing it around the web and found out the issue is coming from Microsoft UI Library and they are aware of the issue but they focus on releasing the Microsoft UI Library 3.0 (https://github.com/Microsoft/microsoft-ui-xaml/issues/559)
So, @yaichenbaum what do you want me to do to fix this? Wait for 3.0 or remove the Microsoft UI Library and use the existing one on Windows SDK and shift the minimal platform up to Windows 10 Version 1809 (The release of Menu bar https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.menubar)

**Comment by yaichenbaum** [comment]
We will wait, being that it is just a design issue and nut function issue I will be closing this issue.
