### ISSUE TITLE
Change The Icon(& Name) To Look More stock

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#367]
**Is your feature request related to a problem? Please describe.**
Quickpad's icon is cool but I hate how it doesn't fit and look like Microsoft would make. 

**Describe the solution you'd like**
Replace the icon with https://filebin.net/eeclj43jpnqpxc8t

**Additional context**
A Name change to something like "Notes" or the names of Wordpad or notepad would also be appreciated.

**Comment by yaichenbaum** [comment]
@diligamer Thank you for bringing this up, Quick Pad already uses a fabric UI icon which is the style Microsoft uses as well for all the new icons they make. Nevertheless, I will look into improving the design.
Unfortunately, I cannot use the name Wordpad, Notepad, or Notes because those are either products from Microsoft or apps already in the store.

**Comment by diligamer** [comment]
The Microsoft apps for notetaking are called "Sticky Notes" and "OneNote". "Notepad" Is taken but "WordPad" Isn't. Windows 10X's Fabric icon for a "notes" app is the one linked.

**Comment by yaichenbaum** [comment]
WordPad is actually built into Windows.

**Comment by yaichenbaum** [comment]
![image](https://user-images.githubusercontent.com/39923744/75069898-2934c680-54c0-11ea-8738-f8465528bd8a.png)

**Comment by sharpninja** [comment]
I like ir
________________________________

**Comment by diligamer** [comment]
Y

**Comment by diligamer** [comment]
This Issue Was closed because it has been solved.
