### ISSUE TITLE
Make the text area have a white background

### ISSUE THREAD

**Issue by diligamer** [UWPCommunity/Quick-Pad#385]
**Is your feature request related to a problem? Please describe.**
Writing on black feels unnatural  

**Describe the solution you'd like**
Make the text box white

**Describe alternatives you've considered**
Setting to light mode

**Comment by yaichenbaum** [comment]
To change the app to light mode,
- Open the settings page in Quick Pad
- Go to theme options
- Choose light mode.

**Comment by diligamer** [comment]
That Is Not What I Asked For. I am talking about 'The Text Box', not the 'App UI'.

**Comment by yaichenbaum** [comment]
I don't have any plans to implement this as an option.

**Comment by diligamer** [comment]
I am Dissapinoted that you have rejected my issue, but I understand that my use case is not needed by a large majority of users.

**Comment by yaichenbaum** [comment]
When is that you want a white background? It wouldn't make sense to have that in dark mode since that wouldn't be dark mode anymore. If you want it in light mode, it is already implemented that way. There is also the option to have an acrylic background for the textbox if you would like, and you can adjust the tint opacity there as well.
