### ISSUE TITLE
Performance drop when using emojis

### ISSUE THREAD

**Issue by DonLuke25** [UWPCommunity/Quick-Pad#409]
**Describe the bug**
Hello, I use Quick Pad to prepare many basic notes, including templates for social media posts and I've noticed, there's a significant performance drop when using emojis in a document. When selecting text, copying/pasting and typing. It must be a longer document. The UI still works well, it's really only when working with the text inside of the document.

**To Reproduce**
Try to have a document with like 100 lines of texts and with like 30-40 emojis inside
Then try to select a larger bulk of text and use CTRL+C. Or type quickly.

**Expected behavior**
No performance drops.

**Desktop:**
 - OS Version: Windows 10 1909 18363.778
 - App version: 4.4.2.0
 - CPU: i7-8700K, 3.70 GHZ
 - RAM: 32 GB
 - GPU: Nvidia GeForce GTX 1080 Ti
 - Samsung SSD drive

**Comment by yaichenbaum** [comment]
Thank you for the issue report, I have been able to reproduce this consistently. I believe the issue lies with the WinUI text controls, there is an open [issue](https://github.com/microsoft/microsoft-ui-xaml/issues/1842) on the WinUI repository requesting support for better handling of larger files. Make sure to upvote the issue on the WinUI repository in order to make this a higher priority to address.

**Comment by DonLuke25** [comment]
>Make sure to upvote the issue on the WinUI repository in order to make this a higher priority for them to address.

Done. Thank you and hopefully it will be possible to fix it!

**Comment by yaichenbaum** [comment]
@DonLuke25 Thank you, I try to keep Quick Pad on the latest version of WinUI, so you should see a fix in Quick Pad shortly after it's fixed from the WinUI end.
