### ISSUE TITLE
Reduce system resource usage when running the app

### ISSUE THREAD

**Issue by yaichenbaum** [UWPCommunity/Quick-Pad#61]
Resource usage between the built in Notepad and Quick Pad is a huge difference, while the two cannot be compared since Quick Pad includes auto save plus other functions, there is definitely more room for improvement and optimizations.
![image](https://user-images.githubusercontent.com/39923744/63235425-5352b680-c207-11e9-8848-ca12553f6af0.png)
I am sure there are a lot of parts of the code that contribute to this issue and it should improve as the code base gets cleaned up but there are probably other areas as well that can be improved and reduce the memory usage.

**Comment by ray1997** [comment]
We could use performance profiler to see where the memory is used.

There are a way to unload unused UI using x:Load
I've test it, before x:Load it take about 63 MB
And after putting in x:Load the app used about 50 MB

FontAndFormat won't be there this next update. So, I suggest for now we should put x:Load="False" on it because it will still load and take some memory.

**Comment by yaichenbaum** [comment]
I think this would be the first step. Next would be to figure out which parts cause memory to be used and optimize that code for performance.

**Comment by yaichenbaum** [comment]
- [ ] Option to adjust how often the auto save timer works, in addition we can also optimize and make sure it only runs if there are unsaved changes.
